### ISSUE TITLE
freerdp /cert-ignore flag has been deprecated

### ISSUE THREAD

**Issue by avanzzzi** [avanzzzi/hypy#26]
The /cert-ignore of xfreerdp command has been deprecated.

The new flag is /cert:ignore.

Linux still has the old flag active but mac version already removed it.

**Comment by ArthurGorgonio** [comment]
Do we need to keep the "old cert style" syntax, `/cert-ignore`, for compatibility reasons?

My idea is add a deprecation warning in the next `hypy` release and remove it in the follow one.

The FreeRDP deprecated (firstly with warnings) the cert-ignore at version 2.0.0. 

see https://github.com/FreeRDP/FreeRDP/blob/2.6.1/ChangeLog#L276
issue: https://github.com/FreeRDP/FreeRDP/pull/5880

**Comment by ArthurGorgonio** [comment]
I just drop the idea related to retro compatibility, we do not have reasons to provide support for a deprecated flag.
